"""Event classes for the event-driven backtesting engine.

Event Flow:
    DataHandler -> MarketEvent -> Strategy -> SignalEvent ->
    Portfolio -> OrderEvent -> ExecutionHandler -> FillEvent -> Portfolio
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum


class EventType(Enum):
    """Types of events in the system."""

    MARKET = "MARKET"
    SIGNAL = "SIGNAL"
    ORDER = "ORDER"
    FILL = "FILL"


class SignalType(Enum):
    """Types of trading signals."""

    LONG = "LONG"
    SHORT = "SHORT"
    EXIT = "EXIT"


class OrderType(Enum):
    """Types of orders."""

    MARKET = "MARKET"
    LIMIT = "LIMIT"


class OrderSide(Enum):
    """Order side (buy or sell)."""

    BUY = "BUY"
    SELL = "SELL"


@dataclass
class Event:
    """Base class for all events."""

    event_type: EventType
    timestamp: datetime


@dataclass
class MarketEvent(Event):
    """Generated when new market data is available.

    This event triggers strategy calculations.
    """

    event_type: EventType = field(default=EventType.MARKET, init=False)

    def __init__(self, timestamp: datetime) -> None:
        self.event_type = EventType.MARKET
        self.timestamp = timestamp


@dataclass
class SignalEvent(Event):
    """Generated by strategy when a trading signal is detected.

    Attributes:
        symbol: The instrument symbol
        signal_type: LONG, SHORT, or EXIT
        strength: Signal strength from 0.0 to 1.0
    """

    symbol: str
    signal_type: SignalType
    strength: float = 1.0
    event_type: EventType = field(default=EventType.SIGNAL, init=False)

    def __init__(
        self,
        timestamp: datetime,
        symbol: str,
        signal_type: SignalType,
        strength: float = 1.0,
    ) -> None:
        self.event_type = EventType.SIGNAL
        self.timestamp = timestamp
        self.symbol = symbol
        self.signal_type = signal_type
        self.strength = strength


@dataclass
class OrderEvent(Event):
    """Generated by portfolio to execute a trade.

    Attributes:
        symbol: The instrument symbol
        order_type: MARKET or LIMIT
        side: BUY or SELL
        quantity: Number of units to trade
        limit_price: Price for limit orders (optional)
    """

    symbol: str
    order_type: OrderType
    side: OrderSide
    quantity: int
    limit_price: float | None = None
    event_type: EventType = field(default=EventType.ORDER, init=False)

    def __init__(
        self,
        timestamp: datetime,
        symbol: str,
        order_type: OrderType,
        side: OrderSide,
        quantity: int,
        limit_price: float | None = None,
    ) -> None:
        self.event_type = EventType.ORDER
        self.timestamp = timestamp
        self.symbol = symbol
        self.order_type = order_type
        self.side = side
        self.quantity = quantity
        self.limit_price = limit_price


@dataclass
class FillEvent(Event):
    """Generated by execution handler after an order is filled.

    Attributes:
        symbol: The instrument symbol
        side: BUY or SELL
        quantity: Number of units filled
        fill_price: Price at which the order was filled
        commission: Commission paid for the trade
    """

    symbol: str
    side: OrderSide
    quantity: int
    fill_price: float
    commission: float
    event_type: EventType = field(default=EventType.FILL, init=False)

    def __init__(
        self,
        timestamp: datetime,
        symbol: str,
        side: OrderSide,
        quantity: int,
        fill_price: float,
        commission: float,
    ) -> None:
        self.event_type = EventType.FILL
        self.timestamp = timestamp
        self.symbol = symbol
        self.side = side
        self.quantity = quantity
        self.fill_price = fill_price
        self.commission = commission
